repos:
  # Prettier for code formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        args: [--write]
        additional_dependencies:
          - prettier@3.3.3
        files: \.(js|jsx|ts|tsx|json|css|scss|md|mdx|yaml|yml)$

  # ESLint for linting
  - repo: local
    hooks:
      - id: eslint
        name: ESLint
        entry: npx eslint
        language: node
        types: [file]
        files: \.(js|jsx|ts|tsx)$
        args: [--fix, --max-warnings=60] # TODO: Bring the max warnings down to zero

  # TODO: Enable typescript checking
  # TypeScript type checking
  #  - repo: local
  #    hooks:
  #      - id: tsc
  #        name: TypeScript Check
  #        entry: npx tsc
  #        language: node
  #        args: [--noEmit]
  #        files: \.(ts|tsx)$
  #        pass_filenames: false

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # Check for files that would conflict in case-insensitive filesystems
      - id: check-case-conflict
      # Check for files that contain merge conflict strings
      - id: check-merge-conflict
      # Check for debugger imports and breakpoint() calls in python
      - id: debug-statements
      # Makes sure files end in a newline and only a newline
      - id: end-of-file-fixer
      # Replaces or checks mixed line endings
      - id: mixed-line-ending
        args: [--fix=lf]
      # Trims trailing whitespace
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      # Check for valid JSON
      - id: check-json
      # Check for valid YAML
      - id: check-yaml
      # Prevent giant files from being committed
      - id: check-added-large-files
        args: [--maxkb=1000]

  # Security checks for dependencies
  - repo: local
    hooks:
      - id: npm-audit
        name: NPM Security Audit
        entry: npm audit
        language: node
        args: [--audit-level=moderate]
        pass_filenames: false
        stages: [pre-commit]

# Global configuration
fail_fast: false
default_stages: [pre-commit]
